server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: micro-parking
  datasource:
    #uri: mongodb://localhost:27017/microservice_parking
    #username: root
  uri: mongodb+srv://root:tpegrupo16@tpearqui:w56qg:mongodb:net/?retryWrites=true&w=majority&appName=TpeArqui
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}